sudo: required

language: generic

services:
  - docker 

before_install:
  -echo "start Createing an images woth dockerfile"
  -docker build -t mailsky2010/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true mailsky2010/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success'"